# Generated by Django 5.0.4 on 2024-06-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('identity', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('student_number', models.CharField(blank=True, max_length=50, null=True)),
                ('attendee_type', models.CharField(choices=[('LCL', 'Local'), ('INTL', 'International'), ('STUD', 'Student')], default='LCL', max_length=30)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Attendees',
            },
        ),
    ]
