# Generated by Django 5.0.4 on 2024-06-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0002_alter_attendees_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='attendee_type',
            field=models.CharField(choices=[('Local', 'Local'), ('International', 'International'), ('Student', 'Student')], default='Local', max_length=30),
        ),
    ]
