# Generated by Django 5.0.6 on 2024-06-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0004_event_speaker_sponsor_testimonial_agenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name_plural': 'Agenda'},
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='organization',
            new_name='organization_name',
        ),
    ]
