# Generated by Django 5.0.6 on 2024-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0005_alter_agenda_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=10000)),
                ('amount', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Panalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=10000)),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='images/')),
                ('summary', models.TextField(max_length=5000)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimony',
            field=models.TextField(max_length=10000),
        ),
    ]
