# Generated by Django 5.0.6 on 2024-06-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0007_booth_booth_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='names',
            new_name='name',
        ),
    ]
