# Generated by Django 5.0.6 on 2024-06-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0009_rename_name_testimonial_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
