# Generated by Django 5.0.6 on 2024-06-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0010_previousvideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('photo_file', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
