# Generated by Django 5.0.6 on 2024-06-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0012_agenda_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={},
        ),
        migrations.CreateModel(
            name='event_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=100)),
                ('day_date', models.DateField()),
                ('day_activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference_planning.agenda')),
            ],
            options={
                'verbose_name_plural': 'Agenda',
            },
        ),
    ]
