# Generated by Django 5.0.6 on 2024-06-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0013_alter_agenda_options_event_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name_plural': 'Agenda'},
        ),
        migrations.AddField(
            model_name='agenda',
            name='day_event',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='event_days',
        ),
    ]
