# Generated by Django 5.0.6 on 2024-06-16 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0015_alter_agenda_day_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='day_event',
        ),
        migrations.CreateModel(
            name='Event_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=100)),
                ('day_date', models.DateField()),
                ('day_activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference_planning.agenda')),
            ],
            options={
                'verbose_name_plural': 'Event_days',
            },
        ),
    ]
