# Generated by Django 5.0.6 on 2024-06-16 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0016_remove_agenda_day_event_event_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_days',
            name='day_activities',
        ),
        migrations.AddField(
            model_name='agenda',
            name='day_event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='conference_planning.event_days'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='activity',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
