# Generated by Django 5.0.6 on 2024-06-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0017_remove_event_days_day_activities_agenda_day_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='day_event',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='conference_planning.event_days'),
        ),
    ]
