# Generated by Django 5.0.6 on 2024-06-16 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0018_alter_agenda_day_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='day_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference_planning.event_days'),
        ),
    ]
