# Generated by Django 5.0.6 on 2024-06-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0019_alter_agenda_day_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='day_event',
        ),
    ]
