# Generated by Django 5.0.6 on 2024-06-16 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0021_delete_event_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=100)),
                ('day_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Event_days',
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='day_event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='conference_planning.event_days'),
        ),
    ]
