# Generated by Django 5.0.6 on 2024-06-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0022_event_days_agenda_day_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('benefits', models.TextField(max_length=100000)),
            ],
        ),
    ]
