# Generated by Django 5.0.6 on 2024-06-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0024_sponsor_sponsorship_sponsorships_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('pdf_document', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sponsorships',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sponsorships',
            name='uploaded_at',
        ),
    ]
