# Generated by Django 5.0.6 on 2024-06-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0025_document_remove_sponsorships_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sponsorship', models.CharField(max_length=5000)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
    ]
