# Generated by Django 5.0.6 on 2024-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0027_countdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='booth_number',
            field=models.IntegerField(default=''),
        ),
    ]
