# Generated by Django 5.0.6 on 2024-06-25 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0030_booth_status_alter_booksponsorship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksponsorship',
            name='sponsorship',
        ),
        migrations.AddField(
            model_name='booksponsorship',
            name='sponsorship_package',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='conference_planning.sponsorships'),
        ),
    ]
