# Generated by Django 5.0.6 on 2024-06-25 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0031_remove_booksponsorship_sponsorship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sponsorships',
            name='amount',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='conference_planning.amount'),
        ),
    ]
