# Generated by Django 5.0.6 on 2024-06-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0034_remove_sponsorships_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorships',
            name='payment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='conference_planning.amount'),
        ),
    ]
