# Generated by Django 5.0.6 on 2024-06-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0037_amount_remove_sponsorships_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksponsorship',
            name='amount',
        ),
        migrations.AddField(
            model_name='booksponsorship',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booksponsorship',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
