# Generated by Django 5.0.6 on 2024-06-27 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0040_floorplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth_space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='booth',
            name='status',
        ),
        migrations.CreateModel(
            name='BookBooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exhibitor_name', models.CharField(max_length=100)),
                ('Company', models.CharField(default='', max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('booth', 'Booth'), ('accessory', 'Accessory')], default='booth', max_length=100)),
                ('status', models.CharField(choices=[('book', 'Book'), ('booked', 'Booked')], default='book', max_length=10)),
                ('Booth', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='conference_planning.booth')),
                ('Booth_space', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='conference_planning.booth_space')),
            ],
        ),
    ]
