# Generated by Django 5.0.6 on 2024-06-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0041_booth_space_remove_booth_status_bookbooth'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('quantity', models.IntegerField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=10000)),
                ('amount', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookbooth',
            name='category',
        ),
        migrations.CreateModel(
            name='BookAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exhibitor_name', models.CharField(max_length=100)),
                ('Company', models.CharField(default='', max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('book', 'Book'), ('booked', 'Booked')], default='book', max_length=10)),
                ('Accessory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='conference_planning.accessory')),
            ],
        ),
    ]
