# Generated by Django 5.0.6 on 2024-06-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0043_attendees_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='category',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('delegate', 'Delegate'), ('exhibitor', 'Exhibitor'), ('student', 'Student'), ('media', 'Media')], default='choose your category', max_length=100),
        ),
    ]
