# Generated by Django 5.0.6 on 2024-06-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0044_alter_attendees_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousConferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(max_length=1000)),
                ('year', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=5000)),
            ],
        ),
    ]
