# Generated by Django 5.0.6 on 2024-07-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0045_previousconferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousvideos',
            name='conference_year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
