# Generated by Django 5.0.6 on 2024-07-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0046_previousvideos_conference_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorships',
            name='payment',
            field=models.CharField(max_length=100),
        ),
    ]
