# Generated by Django 5.0.6 on 2024-07-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0047_alter_sponsorships_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
