# Generated by Django 5.0.6 on 2024-07-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0048_delete_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendees',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=100),
        ),
    ]
