# Generated by Django 5.0.6 on 2024-10-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0050_interns'),
    ]

    operations = [
        migrations.CreateModel(
            name='internship_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images/')),
                ('document', models.FileField(upload_to='uploads/')),
                ('summary', models.TextField(max_length=10000)),
            ],
        ),
    ]
