# Generated by Django 5.0.6 on 2024-10-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0051_internship_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_documents',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
