# Generated by Django 5.0.6 on 2024-10-18 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0055_alter_interns_host_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interns',
            name='Host_Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conference_planning.internship_document'),
            preserve_default=False,
        ),
    ]
