# Generated by Django 5.0.6 on 2026-08-23 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0056_alter_interns_host_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30)),
                ('site_location', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='attendees',
            name='category',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('delegate', 'Delegate'), ('exhibitor', 'Exhibitor'), ('student', 'Student'), ('media', 'Media'), ('partnership', 'Partnership')], default='choose your category', max_length=100),
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('identity', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('Site', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='conference_planning.sites')),
            ],
        ),
    ]
