# Generated by Django 5.0.6 on 2026-08-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0057_sites_alter_attendees_category_sitevisit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sites',
            new_name='Site',
        ),
        migrations.RenameModel(
            old_name='SiteVisit',
            new_name='Site_Visit',
        ),
    ]
