# Generated by Django 5.0.6 on 2026-08-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_planning', '0058_rename_sites_site_rename_sitevisit_site_visit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site_Visit',
            new_name='Visit',
        ),
    ]
